
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using CleanRPG.Systems;

namespace CleanRPG.UI
{
    public class GachaBannerUI : MonoBehaviour
    {
        private Canvas canvas; private RectTransform panel; private Sprite uiSprite; private GachaSystem gacha; private Transform resultsGrid;
        void Awake(){ uiSprite = Resources.GetBuiltinResource<Sprite>("UISprite.psd"); canvas = new GameObject("GachaCanvas").AddComponent<Canvas>(); canvas.renderMode = RenderMode.ScreenSpaceOverlay; canvas.gameObject.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize; canvas.gameObject.AddComponent<GraphicRaycaster>(); panel = CreatePanel(new Vector2(10,-540), new Vector2(760,300), new Vector2(0,1)); panel.gameObject.SetActive(false); gacha = new GachaSystem("featured_v8"); Build(); }
        void Update(){ if (Input.GetKeyDown(KeyCode.F3)) panel.gameObject.SetActive(!panel.gameObject.activeSelf); }
        void Build(){ CreateTMP(panel,"Title","Gacha (F3) — Banner v8", new Vector2(10,-10), 20, true); var btn1 = CreateButton(panel, "Pull 1x", new Vector2(10,-50)); btn1.onClick.AddListener(()=> DoPull(1)); var btn10 = CreateButton(panel, "Pull 10x", new Vector2(120,-50)); btn10.onClick.AddListener(()=> DoPull(10)); var grid = new GameObject("Results", typeof(RectTransform), typeof(Image)); grid.transform.SetParent(panel, false); var rt = grid.GetComponent<RectTransform>(); rt.sizeDelta = new Vector2(740, 200); rt.pivot = new Vector2(0,1); rt.anchoredPosition = new Vector2(10,-90); grid.GetComponent<Image>().sprite = uiSprite; grid.GetComponent<Image>().type = Image.Type.Sliced; grid.GetComponent<Image>().color = new Color(0,0,0,0.25f); resultsGrid = grid.transform; }
        void DoPull(int n){ foreach (Transform t in resultsGrid) GameObject.Destroy(t.gameObject); var items = new List<string>(); for (int i=0;i<n;i++) items.Add(gacha.Pull()); int col=0,row=0; foreach (var id in items){ var card = CreateCard(resultsGrid, id, new Vector2(10 + col*180, -10 - row*90)); col++; if (col>=4){ col=0; row++; } CleanRPG.Systems.InventorySystem.Unlock(id); } }
        RectTransform CreatePanel(Vector2 pos, Vector2 size, Vector2 anchor){ var go=new GameObject("GachaPanel", typeof(RectTransform), typeof(Image)); go.transform.SetParent(canvas.transform,false); var rt=go.GetComponent<RectTransform>(); rt.sizeDelta=size; rt.anchorMin=anchor; rt.anchorMax=anchor; rt.pivot=new Vector2(0,1); rt.anchoredPosition=pos; var img=go.GetComponent<Image>(); img.sprite=Resources.GetBuiltinResource<Sprite>("UISprite.psd"); img.type=Image.Type.Sliced; img.color=new Color(0,0,0,0.55f); return rt; }
        Button CreateButton(Transform parent,string label, Vector2 pos){ var go=new GameObject("Btn", typeof(RectTransform), typeof(Image), typeof(Button)); go.transform.SetParent(parent,false); var rt=go.GetComponent<RectTransform>(); rt.sizeDelta=new Vector2(100,32); rt.pivot=new Vector2(0,1); rt.anchoredPosition=pos; var img=go.GetComponent<Image>(); img.sprite=Resources.GetBuiltinResource<Sprite>("UISprite.psd"); img.type=Image.Type.Sliced; img.color=new Color(0.2f,0.2f,0.2f,0.9f); var btn=go.GetComponent<Button>(); var txt=new GameObject("Label", typeof(RectTransform), typeof(TextMeshProUGUI)); txt.transform.SetParent(go.transform,false); var tr=txt.GetComponent<RectTransform>(); tr.sizeDelta=new Vector2(90,24); tr.pivot=new Vector2(0,1); tr.anchoredPosition=new Vector2(6,-4); var t=txt.GetComponent<TextMeshProUGUI>(); t.text=label; t.fontSize=16; t.color=Color.white; return btn; }
        TextMeshProUGUI CreateTMP(Transform parent,string name,string content, Vector2 pos,int size=16, bool bold=false){ var go=new GameObject(name, typeof(RectTransform), typeof(TextMeshProUGUI)); go.transform.SetParent(parent,false); var rt=go.GetComponent<RectTransform>(); rt.sizeDelta=new Vector2(720,28); rt.pivot=new Vector2(0,1); rt.anchoredPosition=pos; var t=go.GetComponent<TextMeshProUGUI>(); t.text=content; t.fontSize=size; if(bold) t.fontStyle = FontStyles.Bold; t.color=Color.white; return t; }
        Transform CreateCard(Transform parent, string id, Vector2 pos){ var go=new GameObject("Card_"+id, typeof(RectTransform), typeof(Image)); go.transform.SetParent(parent,false); var rt=go.GetComponent<RectTransform>(); rt.sizeDelta=new Vector2(170,80); rt.pivot=new Vector2(0,1); rt.anchoredPosition=pos; var img=go.GetComponent<Image>(); img.sprite=Resources.GetBuiltinResource<Sprite>("UISprite.psd"); img.type=Image.Type.Sliced; img.color=new Color(0.15f,0.15f,0.2f,0.9f); var label=new GameObject("Label", typeof(RectTransform), typeof(TextMeshProUGUI)); label.transform.SetParent(go.transform,false); var lrt=label.GetComponent<RectTransform>(); lrt.sizeDelta=new Vector2(150,70); lrt.pivot=new Vector2(0,1); lrt.anchoredPosition=new Vector2(10,-6); var t=label.GetComponent<TextMeshProUGUI>(); t.text=id; t.fontSize=14; t.color=Color.white; return go.transform; }
    }
}
